name: PR
on:
  pull_request:
    branches:
      - main
      - '*.x'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Setup go for Buf CLI's license-header support
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'
          cache: false # Disable built-in caching as there is no go.mod/go.sum
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/pom.xml') }} # pom.xml contains Buf CLI version
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Java JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'
      - name: Build
        run: ./mvnw --batch-mode verify
